import { Elysia } from "elysia";
import { db } from "../db";
import { tiang } from "../db/schema";

export const exportRoutes = new Elysia({ prefix: "/api/export" })

  .get("/kml", async ({ set }) => {
    const data = await db.select().from(tiang);

    const warna: Record<string, string> = {
      PLN: "ff0000ff",
      Telkom: "ffff6600",
      "ISP Sendiri": "ff00cc00",
      Bambu: "ff666666",
      Besi: "ff888888",
      Lainnya: "ffaaaaaa",
    };

    const stylesDefs = Object.entries(warna)
      .map(
        ([jenis, color]) => `
    <Style id="style_${jenis.replace(/ /g, "_")}">
      <IconStyle>
        <color>${color}</color>
        <scale>1.2</scale>
        <Icon><href>http://maps.google.com/mapfiles/kml/paddle/wht-stars.png</href></Icon>
      </IconStyle>
      <LabelStyle><scale>0.8</scale></LabelStyle>
    </Style>`
      )
      .join("\n");

    const placemarks = data
      .map(
        (item) => `
    <Placemark>
      <name>${item.kode}${item.label ? ` (${item.label})` : ""}</name>
      <description><![CDATA[
        <b>Jenis:</b> ${item.jenis}<br/>
        <b>Kondisi:</b> ${item.kondisi}<br/>
        <b>Catatan:</b> ${item.catatan || "-"}<br/>
        <b>Dibuat oleh:</b> ${item.dibuat_oleh || "Teknisi"}<br/>
        <a href="https://maps.google.com/?q=${item.latitude},${item.longitude}&layer=c&cbll=${item.latitude},${item.longitude}" target="_blank">📷 Street View</a>
      ]]></description>
      <styleUrl>#style_${item.jenis.replace(/ /g, "_")}</styleUrl>
      <Point>
        <coordinates>${item.longitude},${item.latitude},0</coordinates>
      </Point>
    </Placemark>`
      )
      .join("\n");

    const kml = `<?xml version="1.0" encoding="UTF-8"?>
<kml xmlns="http://www.opengis.net/kml/2.2">
  <Document>
    <name>Survey Tiang BITNET</name>
    <description>Generated by Tiang Mapper Pro — tools.ajengmedia.com | Total: ${data.length} tiang</description>
    ${stylesDefs}
    ${placemarks}
  </Document>
</kml>`;

    set.headers["Content-Type"] = "application/vnd.google-earth.kml+xml";
    set.headers["Content-Disposition"] = `attachment; filename="tiang-bitnet-${Date.now()}.kml"`;
    return kml;
  })

  .get("/csv", async ({ set }) => {
    const data = await db.select().from(tiang);

    const header = "ID,Kode,Label,Jenis,Kondisi,Latitude,Longitude,Catatan,Dibuat Oleh,Tanggal\n";
    const rows = data
      .map((item) =>
        [
          item.id,
          item.kode,
          `"${(item.label || "").replace(/"/g, '""')}"`,
          item.jenis,
          item.kondisi,
          item.latitude,
          item.longitude,
          `"${(item.catatan || "").replace(/"/g, '""')}"`,
          item.dibuat_oleh || "Teknisi",
          new Date(item.dibuat_pada).toLocaleDateString("id-ID"),
        ].join(",")
      )
      .join("\n");

    set.headers["Content-Type"] = "text/csv; charset=utf-8";
    set.headers["Content-Disposition"] = `attachment; filename="tiang-bitnet-${Date.now()}.csv"`;
    return "﻿" + header + rows;
  })

  .get("/json", async ({ set }) => {
    const data = await db.select().from(tiang);

    set.headers["Content-Type"] = "application/json";
    set.headers["Content-Disposition"] = `attachment; filename="backup-tiang-${Date.now()}.json"`;
    return JSON.stringify(
      {
        versi: "1.0",
        app: "Tiang Mapper Pro — BITNET",
        diekspor_pada: new Date().toISOString(),
        total: data.length,
        data,
      },
      null,
      2
    );
  });
